### ISSUE TITLE
Update to latest Gnome

### ISSUE THREAD

**Issue by flxzt** [PNDeb/pinenote-gnome-extension#2]
Support for Gnome v45 would be nice to be able to use the extension with Debian testing.

**Comment by m-weigand** [comment]
should be fixed in the main branch. However, I'm not sure when I will be able to upload a new package to the repository.

As a side note, when using trixie, also enable on the custom repository, as is done in this commit:

https://github.com/PNDeb/pinenote-debian-image/commit/37df0d9237dc0f1afb4e49c1f6647e0263b93249

Currently the trixie repo only holds an updated mesa package.

**Comment by flxzt** [comment]
Actually it is Gnome 44 on testing.. 

And the latest commit has a typo (missing `=`) [here](https://github.com/PNDeb/pinenote-gnome-extension/blob/8c3def5bc87230d54d0e40392da14bd36244392f/pnhelper%40m-weigand.github.com/extension.js#L374)

> As a side note, when using trixie, also enable on the custom repository, as is done in this commit:

Nice the update mesa seems to improve the refresh cycles a bit.
